version: 2
jobs:
  build:
    working_directory: /root
    docker:
      - image: tubone24/algolia-docsearch-base
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - run: git clone https://github.com/algolia/docsearch-scraper.git
      - run: cp config.json docsearch-scraper
      - run: cd docsearch-scraper && ./docsearch run config.json
